import type { NextConfig } from "next";
import { withSeoContent } from "@seo/components/next";

const nextConfig: NextConfig = {
  transpilePackages: ["@seo/components", "@m13v/seo-components"],
  async redirects() {
    return [
      { source: "/t/vipasana-meditation", destination: "/t/vipassana-meditation", permanent: true },
      { source: "/t/dhamma-paphulla", destination: "/t/dhamma-paphulla-vipassana-meditation-research-centre", permanent: true },
      { source: "/t/vipassana-meditation-adhd", destination: "/t/vipassana-adhd", permanent: true },
      { source: "/t/vipassana-meditation-delhi", destination: "/t/vipassana-meditation-centre-delhi", permanent: true },
      { source: "/t/delhi-vipassana-centre", destination: "/t/vipassana-centre-in-delhi", permanent: true },
      { source: "/t/vipassana-delhi", destination: "/t/vipassana-centre-in-delhi", permanent: true },
      { source: "/t/vipassana-hyderabad", destination: "/t/vipassana-meditation-hyderabad", permanent: true },
      { source: "/t/vipassana-meditation-centre-hyderabad", destination: "/t/vipassana-meditation-center-hyderabad", permanent: true },
      { source: "/t/vipassana-meditation-centre-in-hyderabad", destination: "/t/vipassana-meditation-center-hyderabad", permanent: true },
      { source: "/t/vipassana-centre-hyderabad", destination: "/t/vipassana-meditation-center-hyderabad", permanent: true },
      { source: "/t/hyderabad-vipassana-centre", destination: "/t/vipassana-meditation-center-hyderabad", permanent: true },
      { source: "/t/vipassana-near-me", destination: "/t/vipassana-meditation-centre-near-me", permanent: true },
      { source: "/t/vipassana-meditation-near-me", destination: "/t/vipassana-meditation-centre-near-me", permanent: true },
      { source: "/t/vipassana-old-student", destination: "/guide/old-student-path", permanent: true },
      { source: "/t/vipassana-volunteer", destination: "/guide/dhamma-service", permanent: true },
      { source: "/t/igatpuri-vipassana-booking", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/igatpuri-vipassana-centre", destination: "/t/igatpuri-vipassana", permanent: true },
      { source: "/t/igatpuri-vipassana-center", destination: "/t/igatpuri-vipassana", permanent: true },
      { source: "/t/igatpuri-meditation-centre", destination: "/t/igatpuri-vipassana", permanent: true },
      { source: "/alternative/transcendental-meditation-vs-vipassana", destination: "/alternative/vipassana-vs-transcendental-meditation", permanent: true },
      { source: "/alternative/vipassana-meditation-vs-transcendental-meditation", destination: "/alternative/vipassana-vs-transcendental-meditation", permanent: true },
      { source: "/alternative/m-ditation-transcendantale-vs-vipassana", destination: "/alternative/vipassana-vs-transcendental-meditation", permanent: true },
      { source: "/alternative/vipassana-vs-zen-meditation", destination: "/alternative/vipassana-vs-zen", permanent: true },
      { source: "/t/vipassana-donation-how-much", destination: "/t/vipassana-donation", permanent: true },
      { source: "/t/vipassana-10-day-course-fee", destination: "/t/vipassana-donation", permanent: true },
      { source: "/t/vipassana-meditation-fees", destination: "/t/vipassana-cost", permanent: true },
      { source: "/t/vipassana-registration-form-online-2026", destination: "/t/vipassana-registration-form-online", permanent: true },
      { source: "/t/vipassana-registration-online", destination: "/t/vipassana-registration-form-online", permanent: true },
      { source: "/t/vipassana-meditation-registration", destination: "/t/vipassana-registration-form-online", permanent: true },
      { source: "/t/buddy-practice", destination: "/t/practice-buddy", permanent: true },
      { source: "/t/accountability-and-practice-buddies", destination: "/t/practice-buddy", permanent: true },
      { source: "/alternative/ai-meditation-apps-vs-daily-vipassana-practice", destination: "/alternative/ai-meditation-apps-vs-vipassana-daily-practice-2026", permanent: true },
      { source: "/t/ai-meditation-apps-for-vipassana-practitioners", destination: "/alternative/ai-meditation-apps-vs-vipassana-daily-practice-2026", permanent: true },
      { source: "/t/rebuild-daily-vipassana-practice-after-course", destination: "/t/after-vipassana-daily-practice-rewire-habits", permanent: true },
      { source: "/t/daily-practice-after-vipassana-course", destination: "/t/after-vipassana-daily-practice-rewire-habits", permanent: true },
      { source: "/t/same-time-same-cushion-daily-sit-habit", destination: "/t/preserving-daily-practice-discipline", permanent: true },
      { source: "/t/vipassana-breath-observation-meditation", destination: "/t/anapana-and-vipassana", permanent: true },
      { source: "/t/vipassana-dangers", destination: "/t/vipassana-danger", permanent: true },
      { source: "/t/is-vipassana-safe", destination: "/t/vipassana-danger", permanent: true },
      { source: "/t/vipassana-zagro-enia", destination: "/t/vipassana-danger", permanent: true },
      { source: "/t/vipassana", destination: "/t/vipassana-meditation", permanent: true },
      { source: "/t/what-is-vipassana-meditation", destination: "/t/vipassana-meditation", permanent: true },
      { source: "/t/is-vipassana-free", destination: "/faq/why-is-vipassana-free", permanent: true },
      { source: "/t/vipassana-10-day-course-registration", destination: "/guide/course-application-tips", permanent: true },
      { source: "/t/vipassana-10-day-course-registration-igatpuri", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/vipassana-igatpuri-apply-online", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/vipassana-meditation-registration-igatpuri", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/igatpuri-meditation-centre-registration", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/igatpuri-vipassana-centre-registration", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/igatpuri-vipassana-centre-booking", destination: "/t/vipassana-igatpuri-registration", permanent: true },
      { source: "/t/vipassana-igatpuri-10-day-course", destination: "/t/vipassana-igatpuri", permanent: true },
      { source: "/t/vipassana-centre", destination: "/t/vipassana-meditation-centre", permanent: true },
      { source: "/t/sitting-group", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/group-sitting", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/vipassana-group-sitting", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/vipassana-group-sitting-near-me", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/vipassana-meditation-1-hour-group-sitting", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/vipassana-meditation-one-hour-group-sitting", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/group-sitting-vipassana", destination: "/guide/group-sittings", permanent: true },
      { source: "/t/vipassana-meditation-benefits-scientific-evidence", destination: "/guide/scientific-evidence", permanent: true },
      { source: "/t/vipassana-and-adhd", destination: "/t/vipassana-adhd", permanent: true },
      { source: "/t/dhammagiri", destination: "/t/vipassana-igatpuri", permanent: true },
      { source: "/t/vipassana-meditation-igatpuri", destination: "/t/vipassana-igatpuri", permanent: true },
      { source: "/t/vipassana-meditation-centre-buddha-smriti-park", destination: "/t/vipassana-centre-patna", permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
          {
            key: "Content-Security-Policy",
            value:
              "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.posthog.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.posthog.com https://s4l.ai; frame-src 'self';",
          },
        ],
      },
    ];
  },
};

export default withSeoContent(nextConfig, { contentDir: "src/app/t" });
