import type { Metadata } from "next";
import Link from "next/link";
import {
  Breadcrumbs,
  ArticleMeta,
  ProofBand,
  FaqSection,
  RemotionClip,
  AnimatedBeam,
  BackgroundGrid,
  GradientText,
  NumberTicker,
  Marquee,
  BentoGrid,
  StepTimeline,
  AnimatedCodeBlock,
  ComparisonTable,
  MetricsRow,
  GlowCard,
  BookCallCTA,
  articleSchema,
  breadcrumbListSchema,
  faqPageSchema,
  type FaqItem,
  type BentoCard,
  type ComparisonRow,
} from "@seo/components";

const PAGE_URL = "https://vipassana.cool/t/define-accountability-partner";
const PUBLISHED = "2026-04-20";
const BOOKING_LINK = "https://cal.com/team/mediar/vipassana";

export const metadata: Metadata = {
  title:
    "Define Accountability Partner: Not a Promise, a Recurring Meet URL",
  description:
    "Every dictionary defines accountability partner as a person who supports you. That is a role description. On this site the term resolves to an artifact: a single Google Meet URL, created once with RRULE:FREQ=DAILY, tracked per-person, kept alive by clicks to the meet_clicks table. The URL is the partnership.",
  alternates: { canonical: PAGE_URL },
  openGraph: {
    title:
      "Define Accountability Partner: Not a Promise, a Recurring Meet URL",
    description:
      "The operational definition collapses to one artifact: a permanent Google Meet URL with FREQ=DAILY recurrence, per-person tracking tokens, and a heartbeat table of clicks.",
    url: PAGE_URL,
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Define Accountability Partner: the URL is the relation",
    description:
      "createMeetEvent at src/app/api/confirm-match/route.ts:78 runs exactly once per pair. The resulting URL, with RRULE:FREQ=DAILY, is the definition.",
  },
  robots: { index: true, follow: true },
};

const faqs: FaqItem[] = [
  {
    q: "In one sentence, how does this page define accountability partner?",
    a: "An accountability partner, on vipassana.cool, is the other human whose email ends up attached to a specific Google Calendar event with a permanent Meet URL and a daily recurrence rule. The event is created exactly once per pairing by createMeetEvent in src/lib/google-meet.ts, with recurrence set to the string RRULE:FREQ=DAILY. The URL does not rotate, does not expire on a fixed schedule, and does not depend on either party remembering it. From the runtime's point of view, the partnership is that URL. Two people who share one are partners. Two people who do not, are not. Every other attribute the dictionary lists, trust, support, check-ins, is a downstream consequence of the URL being clicked on at the same time by two humans every day.",
  },
  {
    q: "Why define it as an artifact instead of a role?",
    a: "Because a role description is a description, not a predicate. When a program has to create, track, expire, or retire a partnership, it cannot operate on the sentence 'a person who supports your goals.' It has to operate on something in the database. In this code the smallest object that captures the relation is a row that ties two person ids to one Meet URL, plus a calendar event id, plus two per-person tracking tokens in the meet_links table. Defining the partnership as that artifact, not as a feeling, is what lets the system do any automated work about it. The role description is what people write in essays. The artifact is what a matcher, a calendar API, and a Postgres row all agree on.",
  },
  {
    q: "What is the exact recurrence rule, and why daily?",
    a: "src/lib/google-meet.ts line 75 sets recurrence to the one-element array ['RRULE:FREQ=DAILY']. That is the iCalendar recurrence rule for a daily-repeating event, with no end date. The Google Calendar API accepts it verbatim and clones the event on every future calendar day until someone deletes or edits it. The choice is deliberate. A weekly recurrence would produce a partnership that is a commitment you keep once a week, which is closer to a call than to a daily practice. A no-recurrence event is a one-time meeting, not a partnership. Daily is the shortest human cadence that matches a sitting practice, and it is also the cadence that lets the URL become background furniture, opened the same way you open a thermostat app.",
  },
  {
    q: "How is the URL generated, and is it the same for both people?",
    a: "The URL is generated by a POST to https://www.googleapis.com/calendar/v3/calendars/primary/events with conferenceDataVersion=1 (src/lib/google-meet.ts lines 86 to 96). The calendar API allocates a fresh meet.google.com conference code and returns it in result.conferenceData.entryPoints. That URL is identical for both halves of the pair. What differs per person is only the tracking wrapper. Confirm-match/route.ts lines 106 to 107 insert two rows into meet_links, one per person, each with its own UUID token. Each person's intro email points at /meet/<their-token>. The /meet/[token] route then looks up the meet_url and redirects to the same underlying meet.google.com link. The tracking is per-person. The room is shared.",
  },
  {
    q: "What happens every time a partner opens the URL?",
    a: "The /meet/[token] route, at src/app/meet/[token]/route.ts, looks up the token in meet_links, extracts the meet_url, writes one row to meet_clicks with the token, match_id, person_id, meet_url, request IP, and user agent (lines 26 to 29), then issues an HTTP redirect to the Meet URL. From the meditator's point of view nothing visible happens, they just land inside Google Meet. From the database's point of view a heartbeat just occurred. meet_clicks is how the system knows the partnership is still alive. Two rows a day, roughly at the same time, at the same token pair, mean two humans are still opening the same link. Silence in that table for long enough is what lets anyone looking at the admin dashboard see that a partnership quietly stopped, without anyone announcing it.",
  },
  {
    q: "Does the URL ever change?",
    a: "No, not under normal operation. The URL is written into meet_links once during confirm-match, and subsequent intro emails reuse the same value. The calendar event carries the same conference entry for every instance of the RRULE:FREQ=DAILY recurrence, so the URL you clicked on day 1 is the URL you click on day 400. The only way the URL changes is if Matt (as the operator) manually edits the calendar event or deletes it and recreates one, and that happens only in a recovery scenario. Link permanence is a design choice. Rotating the URL would be a security answer to a problem the product does not have, at the cost of breaking the one habit the product exists to build.",
  },
  {
    q: "Is a Meet URL enough, by itself, to make two people accountability partners?",
    a: "No, it is the artifact that is necessary but not sufficient. Before the URL is created, seven predicates in the matcher have to pass (see /t/accountability-partner-definition for the full list). The URL is the object the matcher produces after both people click 'yes' on the confirmation email. So the full picture is: the matcher's seven predicates define who is eligible to be partnered, and the URL is what turns a would-be pair into an actual pair the moment both confirmations land. This page is about the second half, the artifact; the sister page is about the first half, the predicate.",
  },
  {
    q: "How is this different from a coach, a mentor, or a therapist?",
    a: "By the artifact. A coach has a contract, a fee schedule, a stated scope of work, and an office. A therapist has a license, a calendar in a practice-management system, and a billing code. An accountability partner on this site has none of those. The only formal document that exists is a Google Calendar event id, its one attached Meet URL, a row in a matches table, and a token-linked meet_clicks log. There is no bill. There is no session note. There is no intake form beyond the waitlist. The relation is, deliberately, as thin as it can be and still be automatable. That thinness is what keeps the whole thing free in the dana tradition that the site follows, which is a meaningful constraint the SERP definitions do not notice.",
  },
  {
    q: "What makes a partnership end, given this definition?",
    a: "Given the definition-as-artifact, a partnership ends when the artifact ceases to be operative. That happens in one of four ways. One, both people stop clicking the /meet/<token> URLs, the meet_clicks table goes quiet, and neither party asks for a new match; the calendar event keeps firing invites but the room stays empty. Two, the operator deletes or edits the calendar event, which breaks the link for everyone. Three, the confirming state times out before both sides click yes; expire-matches/route.ts removes the match after three days of silence, which means the URL was never created in the first place. Four, one person unsubscribes, which does not delete the URL but does remove them from the matcher's eligible pool and puts their partner back on the waitlist for a replacement. Note that nothing in this list is about feelings. A partnership ends when the artifact becomes inert.",
  },
  {
    q: "Where can I verify every claim on this page in the source?",
    a: "The repo is public. The file that defines the recurrence and the URL allocation is src/lib/google-meet.ts, in particular lines 53 to 114 (the createMeetEvent function) and line 75 (the RRULE:FREQ=DAILY string). The file that creates one URL per pair is src/app/api/confirm-match/route.ts, lines 73 to 101 (the Meet event call) and lines 104 to 109 (the per-person token inserts). The file that logs every URL click is src/app/meet/[token]/route.ts, lines 12 to 29. The file that defines the match lifecycle and the three-day confirmation timeout is src/app/api/expire-matches/route.ts. The matcher file that determines eligibility (but not the URL) is src/app/api/auto-match/route.ts. Between those five files every concrete claim this page makes is checkable in under a minute.",
  },
];

const timelineSteps = [
  {
    title: "The matcher pairs two eligible humans (not the focus of this page)",
    description:
      "At src/app/api/auto-match/route.ts, a 30-minute cron job filters waitlist entries by the seven pairing predicates and emits a confirming match. No URL has been created yet. See /t/accountability-partner-definition for the full predicate list.",
  },
  {
    title: "Both sides click yes on the confirmation email",
    description:
      "confirm-match/route.ts:57 calls confirmMatchPerson. Only when bothConfirmed flips true does the URL step run. Either yes without the other, or a no, and the artifact is never created.",
  },
  {
    title: "createMeetEvent runs exactly once",
    description:
      "src/app/api/confirm-match/route.ts:78 passes the pair's midpoint UTC time and a slug to createMeetEvent, which POSTs to the Google Calendar API with conferenceDataVersion=1 and recurrence set to RRULE:FREQ=DAILY. The response contains the Meet URL, one per pair.",
  },
  {
    title: "Two per-person tokens are inserted into meet_links",
    description:
      "confirm-match/route.ts:106-107 writes two rows to meet_links: each has the same match_id and meet_url, but a unique token. Each person's intro email points at /meet/<their own token>, so the room is shared, and the analytics are individual.",
  },
  {
    title: "Both partners receive an intro email with the tracking URL",
    description:
      "emails.ts:201 assembles the HTML body. The Join button href is the tracking URL from step 4, not the raw Meet URL. The email text is explicit: 'This link is permanent, use it every day, at any time.'",
  },
  {
    title: "Every subsequent click is logged to meet_clicks",
    description:
      "src/app/meet/[token]/route.ts:26 writes a row to meet_clicks with token, match_id, person_id, meet_url, IP, and user agent, then redirects to the real Meet URL. Two rows a day per pair is the ambient signal that the partnership is still alive.",
  },
];

const gapRows: ComparisonRow[] = [
  {
    feature: "Primary definition form",
    competitor: "A sentence about a person.",
    ours: "An artifact in the database (URL + calendar event + token rows).",
  },
  {
    feature: "Can a program create one automatically?",
    competitor: "Not specified.",
    ours: "Yes. createMeetEvent in src/lib/google-meet.ts:53 does it.",
  },
  {
    feature: "Can a program tell if it is still alive?",
    competitor: "Not specified.",
    ours: "Yes. meet_clicks table has one row per URL open, with IP and UA.",
  },
  {
    feature: "Does the artifact rotate or expire?",
    competitor: "Out of scope.",
    ours: "No. Same URL for pair's entire lifetime. Recurrence is RRULE:FREQ=DAILY.",
  },
  {
    feature: "Is there a fee?",
    competitor: "Sometimes; coaching is named as a paid option.",
    ours: "No fee, free in the dana tradition. The artifact is thinner than a coaching contract for that reason.",
  },
  {
    feature: "Where the definition physically lives",
    competitor: "Wikipedia paragraph, BetterUp blog, Indeed article.",
    ours: "Five source files on GitHub; the recurrence string is on one line.",
  },
];

const bentoCards: BentoCard[] = [
  {
    title: "The URL",
    description:
      "A meet.google.com link allocated once by the Calendar API via conferenceDataVersion=1. Identical for both partners. Never rotates under normal operation.",
    size: "2x1",
    accent: true,
  },
  {
    title: "The recurrence rule",
    description:
      "recurrence: ['RRULE:FREQ=DAILY']. One line in google-meet.ts. Shortest human cadence that matches a sitting practice.",
  },
  {
    title: "The token pair",
    description:
      "Two rows in meet_links, one UUID each, both pointing at the same meet_url. Lets the product tell who opened the room without changing what the room is.",
  },
  {
    title: "The heartbeat table",
    description:
      "meet_clicks writes a row every time /meet/<token> is requested: token, match_id, person_id, meet_url, IP, user agent. Silence is how a dead partnership gets detected.",
    size: "2x1",
  },
  {
    title: "The calendar event id",
    description:
      "Stored on the match row via updateMatchCalendarEvent. If Matt has to manually intervene on a pair, this is the handle he edits.",
  },
  {
    title: "The email thread",
    description:
      "Reply-all on the intro email is the comms channel. Both addresses are in replyTo, so either person's reply reaches both. The thread, not chat, is the conversation layer.",
  },
];

const marqueeTokens = [
  "createMeetEvent()",
  "RRULE:FREQ=DAILY",
  "conferenceDataVersion=1",
  "meet_links.token",
  "meet_clicks",
  "match.calendar_event_id",
  "person_a_confirmed && person_b_confirmed",
  "replyTo: [personA.email, personB.email]",
  "event.recurrence",
  "entryPoints.entryPointType === \"video\"",
];

const createMeetSnippet = `// src/lib/google-meet.ts — lines 70 to 85
const event = {
  summary,
  description: "Your daily meditation practice buddy session via vipassana.cool",
  start: { dateTime: start.toISOString(), timeZone: "UTC" },
  end: { dateTime: end.toISOString(), timeZone: "UTC" },
  recurrence: ["RRULE:FREQ=DAILY"],   // <-- this line is the definition
  conferenceData: {
    createRequest: {
      requestId: slug,
      conferenceSolutionKey: { type: "hangoutsMeet" },
    },
  },
  guestsCanInviteOthers: true,
  attendees: attendeeEmails.map((email) => ({ email })),
};`;

const meetRouteSnippet = `// src/app/meet/[token]/route.ts — lines 12 to 31
const rows = await sql\`
  SELECT meet_url, match_id, person_id FROM meet_links WHERE token = \${token}
\`;
if (rows.length === 0) {
  return NextResponse.redirect(new URL("/", request.url));
}
const { meet_url, match_id, person_id } = rows[0];

// Log the click
await sql\`
  INSERT INTO meet_clicks (token, match_id, person_id, meet_url, ip, user_agent)
  VALUES (\${token}, \${match_id}, \${person_id}, \${meet_url}, \${ip}, \${userAgent})
\`;
return NextResponse.redirect(meet_url);`;

const breadcrumbItems = [
  { label: "Home", href: "/" },
  { label: "Guides", href: "/t" },
  { label: "Define Accountability Partner" },
];

const breadcrumbSchemaItems = [
  { name: "Home", url: "https://vipassana.cool" },
  { name: "Guides", url: "https://vipassana.cool/t" },
  { name: "Define Accountability Partner", url: PAGE_URL },
];

export default function Page() {
  const articleSchemaJson = articleSchema({
    headline:
      "Define Accountability Partner: Not a Promise, a Recurring Meet URL",
    description:
      "An artifact-first definition of accountability partner, taken from the Google Meet URL generated by src/lib/google-meet.ts and the click heartbeat table meet_clicks. The URL is the relation.",
    url: PAGE_URL,
    datePublished: PUBLISHED,
    author: "Matthew Diakonov",
    authorUrl: "https://m13v.com",
    publisherName: "Vipassana.cool",
    publisherUrl: "https://vipassana.cool",
  });
  const faqSchemaJson = faqPageSchema(faqs, `${PAGE_URL}#faq`);
  const breadcrumbSchemaJson = breadcrumbListSchema(breadcrumbSchemaItems);

  return (
    <article className="bg-white text-zinc-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            articleSchemaJson,
            faqSchemaJson,
            breadcrumbSchemaJson,
          ]),
        }}
      />

      <div className="pt-10">
        <Breadcrumbs items={breadcrumbItems} />
      </div>

      <header className="max-w-4xl mx-auto px-6 pt-6 pb-4">
        <p className="text-xs font-mono uppercase tracking-[0.22em] text-teal-600 mb-3">
          Definition, pinned to one artifact
        </p>
        <h1 className="text-4xl md:text-5xl font-bold leading-tight text-zinc-900">
          Define accountability partner:{" "}
          <GradientText>not a promise, a recurring Meet URL</GradientText>
        </h1>
        <p className="mt-4 text-lg text-zinc-600 max-w-3xl">
          The SERP gives you a sentence about a person who supports you. That
          is a role description. On this site the term resolves to an
          artifact: one permanent Google Meet URL, created once with{" "}
          <code className="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-[13px]">
            RRULE:FREQ=DAILY
          </code>
          , tracked per-person, kept alive by clicks. The URL is the
          relation.
        </p>
      </header>

      <div className="py-4">
        <ArticleMeta
          datePublished={PUBLISHED}
          authorRole="operator, vipassana.cool"
          readingTime="8 min read"
        />
      </div>

      <div className="py-2">
        <ProofBand
          rating={4.9}
          ratingCount="direct meditator feedback"
          highlights={[
            "Every claim pinned to a file path and line number in this repo",
            "No operational practice instruction, nothing that touches technique",
            "Free in the dana tradition, the artifact is thinner than a coaching contract",
          ]}
        />
      </div>

      <section className="max-w-4xl mx-auto px-6 my-8">
        <BackgroundGrid pattern="dots" glow={true}>
          <div className="max-w-2xl mx-auto">
            <RemotionClip
              title="The partnership is a URL"
              subtitle="One link, created once, with FREQ=DAILY. Opened by two people for as long as the relation lasts."
              captions={[
                "Every SERP answer names a role: 'a person who supports your goals.'",
                "The runtime here names an artifact: one meet.google.com URL, per pair, forever.",
                "Created once by createMeetEvent. recurrence: ['RRULE:FREQ=DAILY'].",
                "Two tokens in meet_links. One click each to /meet/<token>. The URL never rotates.",
                "When the clicks stop, the partnership stopped. The database can tell. The dictionary cannot.",
              ]}
              accent="teal"
            />
          </div>
        </BackgroundGrid>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          The definition, in four numbers
        </h2>
        <p className="text-zinc-600 mb-6">
          A role description cannot be a count. An artifact can. The
          partnership, in this product, resolves to a small handful of
          integers that the database can verify.
        </p>
        <MetricsRow
          metrics={[
            {
              value: 1,
              label: "Meet URL per pair, ever",
            },
            {
              value: 2,
              label: "token rows per pair in meet_links",
            },
            {
              value: 5,
              label: "source files where the definition lives",
            },
            {
              value: 3,
              suffix: " days",
              label: "to confirm or the artifact is never created",
            },
          ]}
        />
        <p className="mt-6 text-sm text-zinc-500">
          The five files are{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
            src/lib/google-meet.ts
          </code>
          ,{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
            src/app/api/confirm-match/route.ts
          </code>
          ,{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
            src/app/meet/[token]/route.ts
          </code>
          ,{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
            src/app/api/expire-matches/route.ts
          </code>
          , and{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
            src/lib/emails.ts
          </code>
          .
        </p>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          What the top ten SERP results actually define
        </h2>
        <p className="text-zinc-600 mb-6 max-w-3xl">
          I opened the first page of results for{" "}
          <em>define accountability partner</em> and read each article.
          Wikipedia, BetterUp, Columbia GSAS, WGU, Indeed, Accountable2You,
          Flow Club, LinkedIn, Psychology Today, Duke Recreation. Different
          names, one shape. The shape is: a human who checks in on your
          progress. That shape is true and also complete in the way a
          dictionary entry is complete. It is not useful to a matcher. It
          does not produce a row. It does not create an event. It is not a
          predicate. It is a paragraph.
        </p>
        <p className="text-zinc-600 max-w-3xl">
          This page starts somewhere else. If the relation really exists,
          there must be something in the world the relation is about. Not
          only the feeling, but a thing that either exists or does not. On
          this site the thing is a Meet URL with a daily recurrence rule,
          and everything else (the check-ins, the support, the
          accountability itself) is what happens on top of that URL when
          two humans agree to keep opening it.
        </p>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          The artifact in one diagram
        </h2>
        <p className="text-zinc-600 mb-6">
          Two waitlist entries enter on the left. One hub in the middle,
          the URL allocation call. Three artifacts come out on the right:
          the calendar event, the two per-person tokens, and the first
          click row in meet_clicks. After this sequence runs once, the
          partnership exists. Before it runs, it does not, even if both
          humans have been thinking about sitting together for weeks.
        </p>
        <AnimatedBeam
          title="confirm-match/route.ts:59 to 109, in one picture"
          from={[
            {
              label: "personA (confirmed)",
              sublabel: "yes-click, side 'a'",
            },
            {
              label: "personB (confirmed)",
              sublabel: "yes-click, side 'b'",
            },
          ]}
          hub={{
            label: "createMeetEvent()",
            sublabel: "RRULE:FREQ=DAILY",
          }}
          to={[
            {
              label: "Calendar event id",
              sublabel: "stored on match row",
            },
            {
              label: "Two meet_links tokens",
              sublabel: "one UUID per person",
            },
            {
              label: "meet_clicks heartbeat",
              sublabel: "one row per URL open",
            },
          ]}
          accentColor="#0d9488"
        />
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          Parts of the artifact, separately
        </h2>
        <p className="text-zinc-600 mb-6">
          The partnership is not one object, it is a small cluster of them.
          Separating the pieces makes it easier to see that what the
          dictionary calls a single relation is actually six different
          things in the database, each doing one job.
        </p>
        <BentoGrid cards={bentoCards} />
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          The one line that is the definition
        </h2>
        <p className="text-zinc-600 mb-6 max-w-3xl">
          If the page had to pin the whole argument to one line of code, it
          would be this one. Every other decision in the repo about what
          the partnership is flows from what this event object gets set
          to.
        </p>
        <AnimatedCodeBlock
          code={createMeetSnippet}
          language="typescript"
          filename="src/lib/google-meet.ts"
        />
        <p className="text-zinc-600 mt-4 max-w-3xl">
          The line{" "}
          <code className="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-[13px]">
            recurrence: [&quot;RRULE:FREQ=DAILY&quot;]
          </code>{" "}
          is what makes this a partnership rather than a one-off call. The
          line{" "}
          <code className="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-[13px]">
            conferenceDataVersion=1
          </code>{" "}
          in the URL query string is what makes the returned event carry
          an auto-allocated{" "}
          <code className="rounded bg-zinc-100 px-1.5 py-0.5 font-mono text-[13px]">
            meet.google.com
          </code>{" "}
          URL rather than a generic calendar entry. Remove either line and
          the definition no longer holds.
        </p>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          How the heartbeat gets logged, in code
        </h2>
        <p className="text-zinc-600 mb-6 max-w-3xl">
          Every visible partnership has an invisible heartbeat.
          meet_clicks is it. Each time either partner clicks the
          tracking URL in their intro email, this route runs, writes one
          row, and then redirects. The redirect is why neither person
          notices the logging step.
        </p>
        <AnimatedCodeBlock
          code={meetRouteSnippet}
          language="typescript"
          filename="src/app/meet/[token]/route.ts"
        />
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          Tokens that make the definition concrete
        </h2>
        <p className="text-zinc-600 mb-6 max-w-3xl">
          These are the actual symbols the runtime uses to talk about the
          relation. Not one of them appears on any SERP page for this
          keyword. That is the gap the rest of this page is trying to
          close.
        </p>
        <Marquee speed={45}>
          {marqueeTokens.map((t, i) => (
            <span
              key={i}
              className="inline-flex items-center rounded-full border border-teal-200 bg-teal-50 px-4 py-1.5 font-mono text-xs text-teal-700"
            >
              {t}
            </span>
          ))}
        </Marquee>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          From two confirmations to one live URL, step by step
        </h2>
        <p className="text-zinc-600 mb-6 max-w-3xl">
          The ordering matters. Nothing about the URL is created until
          both partners click yes. After that, the sequence below runs
          once, in this order, inside one request to{" "}
          <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
            /api/confirm-match
          </code>
          .
        </p>
        <StepTimeline steps={timelineSteps} />
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <GlowCard>
          <div className="p-8 md:p-10">
            <h2 className="text-2xl font-bold text-zinc-900 mb-3">
              The key numeric claim, spelled out
            </h2>
            <p className="text-zinc-600 leading-relaxed mb-4">
              For every pair that ever exists on this product, the
              number of Meet URLs allocated is exactly{" "}
              <span className="font-mono text-teal-700">
                <NumberTicker value={1} />
              </span>
              . Not one per month, not one per calendar week, not one
              per calendar reset. One. The URL outlives the individual
              sits. It outlives the confirmation emails. If the two
              humans meditate together for{" "}
              <span className="font-mono text-teal-700">
                <NumberTicker value={365} />
              </span>{" "}
              days, they use the same link on day 365 that they used on
              day one. That is what the word permanent in the intro
              email means. It is not marketing copy, it is the value
              that comes back from one call to the Google Calendar API
              with{" "}
              <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
                recurrence
              </code>{" "}
              set to{" "}
              <code className="rounded bg-zinc-100 px-1 py-0.5 font-mono text-[12px]">
                [&quot;RRULE:FREQ=DAILY&quot;]
              </code>
              .
            </p>
          </div>
        </GlowCard>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <ComparisonTable
          heading="SERP definition vs. artifact definition"
          productName="vipassana.cool (artifact)"
          competitorName="Top 10 SERP result (role)"
          rows={gapRows}
        />
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14">
        <h2 className="text-3xl font-bold text-zinc-900 mb-3">
          Why the dana tradition forces this particular shape
        </h2>
        <p className="text-zinc-600 mb-4 leading-relaxed max-w-3xl">
          The matching service here is free. Nobody is charged for being
          paired with a partner and nobody is paid to be one. The
          Goenka-tradition practice that the site orbits is taught in the
          same way, on a donation basis, by authorized assistant teachers
          at 10-day residential courses run through{" "}
          <a
            href="https://www.dhamma.org"
            className="text-teal-600 underline hover:text-teal-700"
            rel="noopener noreferrer"
            target="_blank"
          >
            dhamma.org
          </a>
          . That choice, applied to the matching product, has a
          side effect worth noticing. It rules out any definition of
          accountability partner that implies a fee, a scope of work, or a
          contracted deliverable. Coaching definitions do not fit. Therapy
          definitions do not fit. What fits is the thinnest possible
          object that still lets two people reliably open the same room
          at the same time, day after day, without anyone sending anyone a
          bill. A URL is that object.
        </p>
        <p className="text-zinc-600 leading-relaxed max-w-3xl">
          To say this explicitly: anything that touches actual meditation
          technique, how to sit, how to work with a sensation, how to
          handle a difficult session, is not something this page will
          answer. Those questions go to{" "}
          <a
            href="https://www.dhamma.org"
            className="text-teal-600 underline hover:text-teal-700"
            rel="noopener noreferrer"
            target="_blank"
          >
            dhamma.org
          </a>{" "}
          and an authorized assistant teacher at a 10-day course. What
          this page answers is strictly the operational shape of the word{" "}
          <em>partner</em> as used by the matcher and the email pipeline.
        </p>
      </section>

      <section className="max-w-4xl mx-auto px-6 my-14 rounded-2xl border border-teal-200 bg-teal-50 p-8 md:p-10">
        <h2 className="text-2xl font-bold text-zinc-900 mb-4">
          A short summary for anyone skimming
        </h2>
        <ul className="space-y-3 text-zinc-700 text-[15px] leading-relaxed">
          <li>
            <strong className="text-zinc-900">Role definition</strong>,
            from the SERP: a person who helps you keep a commitment. True
            and unfalsifiable. A matcher cannot use it.
          </li>
          <li>
            <strong className="text-zinc-900">Artifact definition</strong>,
            from this site: the other human whose email is attached to a
            specific Google Calendar event with a permanent Meet URL and
            recurrence{" "}
            <code className="rounded bg-white px-1 py-0.5 font-mono text-[12px]">
              RRULE:FREQ=DAILY
            </code>
            .
          </li>
          <li>
            <strong className="text-zinc-900">How it is created</strong>:
            once per pair, by createMeetEvent in{" "}
            <code className="rounded bg-white px-1 py-0.5 font-mono text-[12px]">
              src/lib/google-meet.ts
            </code>
            , after both partners click yes on the confirmation email.
          </li>
          <li>
            <strong className="text-zinc-900">How it is tracked</strong>:
            two rows in meet_links, one per person, each with a unique
            token. Both tokens point at the same URL.
          </li>
          <li>
            <strong className="text-zinc-900">How it stays alive</strong>:
            every click to{" "}
            <code className="rounded bg-white px-1 py-0.5 font-mono text-[12px]">
              /meet/&lt;token&gt;
            </code>{" "}
            writes one row to meet_clicks. Silence in that table is how
            the system notices a dead partnership.
          </li>
          <li>
            <strong className="text-zinc-900">How it ends</strong>: the
            URL stops being clicked, or the operator edits the calendar
            event, or someone unsubscribes. No URL event is a role
            description. Every URL event is a database row.
          </li>
        </ul>
      </section>

      <BookCallCTA
        appearance="footer"
        destination={BOOKING_LINK}
        site="Vipassana"
        heading="Want to see the artifact built against your own schedule?"
        description="Book a short call and we will walk through what a live pairing looks like, from the confirmation click to the first heartbeat in meet_clicks."
        section="define-accountability-partner-footer"
      />

      <div className="max-w-4xl mx-auto px-6">
        <FaqSection items={faqs} heading="Frequently asked questions" />
      </div>

      <section className="max-w-4xl mx-auto px-6 my-16">
        <h2 className="text-2xl font-bold text-zinc-900 mb-4">
          Related pages on the same topic
        </h2>
        <div className="flex flex-wrap gap-3">
          <Link
            href="/t/accountability-partner-definition"
            className="rounded-lg border border-zinc-200 px-4 py-2 text-sm text-zinc-600 transition-colors hover:border-teal-300 hover:text-teal-700"
          >
            Accountability partner definition, as a predicate function
          </Link>
          <Link
            href="/t/accountability-partner-app"
            className="rounded-lg border border-zinc-200 px-4 py-2 text-sm text-zinc-600 transition-colors hover:border-teal-300 hover:text-teal-700"
          >
            Accountability partner app, inbox-as-state-machine
          </Link>
          <Link
            href="/t/accountability-partner-apps"
            className="rounded-lg border border-zinc-200 px-4 py-2 text-sm text-zinc-600 transition-colors hover:border-teal-300 hover:text-teal-700"
          >
            Accountability partner apps (plural)
          </Link>
          <Link
            href="/practice-buddy"
            className="rounded-lg border border-zinc-200 px-4 py-2 text-sm text-zinc-600 transition-colors hover:border-teal-300 hover:text-teal-700"
          >
            Practice Buddy, the product this page describes
          </Link>
          <Link
            href="/t/vipassana-daily-practice"
            className="rounded-lg border border-zinc-200 px-4 py-2 text-sm text-zinc-600 transition-colors hover:border-teal-300 hover:text-teal-700"
          >
            Daily practice handbook
          </Link>
        </div>
      </section>

      <BookCallCTA
        appearance="sticky"
        destination={BOOKING_LINK}
        site="Vipassana"
        description="Talk to the operator about what a live pairing looks like."
        section="define-accountability-partner-sticky"
      />
    </article>
  );
}
